Add amd64 bit to machine
bobuhiro11/gokvm pull request #104
Opened 2023-01-13 17:56 UTC by rminnich

This change allows callers of setup to specify
amd64.

This includes initial page tables and long
mode setup so we can start kernel at the
64-bit entry point.

It also includes support for KVM_TRANSLATE, which
is incredibly useful for debug.

golangci-lint is making a lot of bogus complaints.

Add a memsize flag, -m

usage
-m number -- default units are gigabytes

-m number[gGmMkK]

units of GiB, MiB, or KiB

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

2023-01-13 17:59 UTC, rminnich commented
I've flagged all the golangci-lint anti-patterns and issues, because, I know that when I import this into Google again, the things golangci-lint requires will clash with google coding standards.

2023-01-13 20:01 UTC, rminnich commented
I notice each CI involves a full kernel build. I'd suggest putting a binary of the kernel somewhere and skipping this step. It will make CI run in seconds, not minutes.

2023-01-13 20:02 UTC, rminnich commented
I'm happy to host the kernel at github.com/linuxboot/bins if you want, we have many kernels there.

2023-01-13 20:27 UTC, rminnich commented
WOOO HOOOOOO! 64-bit and ELF support now!

2023-01-13 20:28 UTC, rminnich commented
I did resolve all the golangci-lint issues, though some of its complaints are a bit questionable :-)

That's ok, better to have it than not to have it :-)

2023-01-18 05:23 UTC, bobuhiro11 requested changes
Thanks for the great improvement of loading the ELF kernel.
It seems to work correctly.
I have written some comments inline for you to check.
```bash
ubuntu2004thinkpad:~/gokvm$ file _linux/vmlinux _linux/arch/x86/boot/bzImage
_linux/vmlinux:               ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=4acaf060bebd9131d2f051de66b4c5607473919a, with debug_info, not stripped
_linux/arch/x86/boot/bzImage: Linux kernel x86 boot executable bzImage, version 5.14.3 (bobuhiro11@ubuntu2004thinkpad) #1 SMP Wed Jan 18 02:11:50 UTC 2023, RO-rootFS, swap_dev 0x2, Normal VGA

ubuntu2004thinkpad:~/gokvm$ sudo go run . -k _linux/vmlinux
ubuntu2004thinkpad:~/gokvm$ sudo go run . -k _linux/arch/x86/boot/bzImage
```

2023-01-18 06:08 UTC, rminnich commented
Thanks for the review!! I will work on this tomorrow.

2023-01-18 16:47 UTC, rminnich commented on go.mod
> +	golang.org/x/tools v0.5.0 // indirect
done

2023-01-18 16:47 UTC, rminnich commented on machine/machine.go
> +//	0x40000000    +------------------+
done. I wonder why that happened?

2023-01-18 16:49 UTC, rminnich commented on machine/machine.go
> +		DefaultKernelAddr = uint64(0x100000)
done

2023-01-18 16:54 UTC, rminnich commented on machine/machine.go
> +		offset := int(bootParam.Hdr.SetupSects+1) * 512
done

2023-01-18 16:57 UTC, rminnich commented on kvm/kvm.go
> +// not to work. It is based on working code from the linuxboot Voodoo project.
I am generally worried about URLs in comments, and I wrote that code, and it's very basic, and that code was broken: I don't think we need that comment. I hope that is OK?

2023-01-18 16:58 UTC, rminnich commented on flag/flag.go
> +	flag.StringVar(&disk, "d", "/dev/zero", "path of disk file Var(&disk,for /dev/vda)")
done

2023-01-19 02:25 UTC, bobuhiro11 approved these changes
Looks good. Thanks for your cooperation!

It took about 10 minutes to build the kernel. If there is no change in the kernel build config, it will be tuned so that it is just a simple download. I'll do that in another pull request.

2023-01-19 02:25 UTC, bobuhiro11 commented on machine/machine.go
> +		bootParam, err = bootparam.New(kernel)
If the bootparams are not present in the ELF, it seems fine to skip them.
Thanks!

2023-01-19 02:25 UTC, bobuhiro11 commented on kvm/kvm.go
> +// not to work. It is based on working code from the linuxboot Voodoo project.
Sure. It's fine as is.

2023-01-19 02:25 UTC, merged